[pytest]
pythonpath = .
addopts = -ra
 --html=myreport.html --self-contained-html --capture=tee-sys

 #--alluredir=reports/allure-results
markers =
    evaluation: offline product-recording/evaluator checks
